[project]
name = "gold-aligner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cryoet-alignment>=0.0.8",
    "imodmodel>=0.0.15",
    "matplotlib>=3.10.1",
    "mrcfile>=1.5.4",
    "pyqt6>=6.8.1",
    "scikit-image>=0.21.0",
    "scipy>=1.10.1",
    "torch-affine-utils>=0.1.0",
]

[project.scripts]
gold-aligner = "gold_aligner:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
